### ISSUE TITLE
macOS Users Need to Edit .zshrc Instead of .bashrc in the Installation Instructions

### ISSUE THREAD

**Issue by farzeennadeem** [djgroen/flee#112]
<img width="686" alt="image" src="https://github.com/user-attachments/assets/150e56cc-a2f9-405f-bda8-317ac0360c41">

While following the installation tutorial for Flee on macOS, I encountered an issue at the step where I needed to edit the .bashrc file. Since macOS uses Zsh as the default shell starting from macOS Catalina, there is no .bashrc file by default. Instead, I had to edit the .zshrc file for the changes to take effect.

Suggested Fix: In the installation instructions, include a note for macOS users, like: "For macOS users, use .zshrc instead of .bashrc to add the environment variables."

**Comment by djgroen** [comment]
@cspgdds Could you double-check if this solution works? Or should the default shell be changed to `bash` here?

**Comment by cspgdds** [comment]
@djgroen It is checked and added to the documentation
