### ISSUE TITLE
Update technical documentation of the use cases

### ISSUE THREAD

**Issue by alirezajahani60** [djgroen/flee#20]
Regarding technical documentation, I noticed when I was very new in using flee as a novice user, there is some complicated or incomplete documentation. For instance, the recent issue I noticed is about multiscale modelling and data preparation for it. I think we need completely guide users on how to do that.

**Comment by djgroen** [comment]
@alirezajahani60 Is this still an issue in the current documentation?

**Comment by alirezajahani60** [comment]
@djgroen No, I added the full documentation for multiscale simulations.
