### ISSUE TITLE
Missing libraries

### ISSUE THREAD

**Issue by alirezajahani60** [djgroen/flee#25]
I noticed the following libraries have been removed from ssudan_mscalecity.py. 

- outputanalysis.analysis
- analyze_graph

Removing the latter one is alright, because it is for debugging, 
but what about outputanalysis.analysis? It is used for output files.

**Comment by djgroen** [comment]
Hamid re-arranged a range of files, and I believe the outputanalysis.analysis module is no longer necessary either... Are you still using it in the code anywhere?

**Comment by alirezajahani60** [comment]
Yes, in lines 176 and 177, it uses rel_error() and abs_error(). However, if Hamid has developed better alternatives, I can replace them.

**Comment by djgroen** [comment]
I believe we have resolved this issue now :).
