### ISSUE TITLE
Having more input files in Flee tutorials

### ISSUE THREAD

**Issue by alirezajahani60** [djgroen/flee#26]
The current version of Flee tutorial documents hasn't updated and reflected the new input files for simulations. Here is the new structure of input files which will be added to the tutorial:

- > source_data (directory)
- > - data_layout.csv
- > - refugees.csv
- > - country_name-camp_name.csv
- > closures.csv
- > conflict_period.csv
- > conflicts.csv
- > coupled_locations.csv (for multiscale and coupled simulations)
- > locations.csv
- > registration_corrections.csv
- > routes.csv

Besides, it is worth to add that for coupled multiscale simulations, there is a need to have two files for the above input files reflecting macro and micro models inputs.

**Comment by djgroen** [comment]
I believe this has been done a while ago :).
