### ISSUE TITLE
The population of conflict zones in location.csv doesn't affect the results (mscale)

### ISSUE THREAD

**Issue by alirezajahani60** [djgroen/flee#29]
During test executions with test input files of ssudan-mscale-test, I forgot to change the population from the original number to the test number and when I found that I realized that the population of conflict zones in location.csv hasn't affected the results before and after the correction the population. I wonder why this happens and how the population shouldn't affect the results?

**Comment by djgroen** [comment]
I think you set TakeRefugeesFromPopulation to False. In this case, it's the ratio between the populations of the different conflict zones that matters.

If you reduce all populations by a factor 100 for the test case then, there will indeed be no change in the results.
