### ISSUE TITLE
remove_forced_redirection implementation

### ISSUE THREAD

**Issue by cspgdds** [djgroen/flee#30]
An automated version of Burundi (2015) conflict has a forced redirection which was removed after certain days: https://github.com/djgroen/FabFlee/blob/master/config_files/burundi/input_csv/closures.csv 

Currently, it is added in the closures.csv file but not implemented in the Flee code.

For reference, hard-coded version of Burundi run.py file  
https://github.com/djgroen/FabFlee/blob/57dbca6ceeccd72bc6adb8d2375cc310fe0bca2a/config_files/validation/SWEEP/oldstyle_burundi/run.py#L173

**Comment by djgroen** [comment]
This is now in the code.
