### ISSUE TITLE
Make a doc page for simsetting.yml

### ISSUE THREAD

**Issue by djgroen** [djgroen/flee#49]
It's largely documented in SimulationSettings.py, but that's not a useful page. Perhaps we should have a ReadTheDocs page for it?

@cspgdds would you have time to make such a page?

**Comment by cspgdds** [comment]
@djgroen yes, I can prepare a page for simsetting.yml

**Comment by djgroen** [comment]
With thanks to @cspgdds (https://flee.readthedocs.io/en/master/Simulation_settings/) I can close this now.
