### ISSUE TITLE
Add new location definition for IDP camps

### ISSUE THREAD

**Issue by djgroen** [djgroen/flee#60]
With a default move chance of 1.0

name = "idpcamp"

**Comment by djgroen** [comment]
I added support for this now. Please test :).

**Comment by djgroen** [comment]
Relevant commits are:
ac6815e91f7be96df2c99c8632661da19f9df530
98eafc37b7a47cc7df98ef4a07c4e558e041c307
90894bf03903e60d59e762705c4a3781f388a872

**Comment by djgroen** [comment]
@cspgdds Just to let you know: idpcamps are considered camps, which means that they do need a validation CSV file (which can be empty) AND that they can have refugees/population inserted in them on Day 0 in the same way that normal camps have.

Btw. does this feature work well for you and the Columbia team?

**Comment by djgroen** [comment]
@cspgdds 

It does include values for IDP camps, but it will calculate totals and errors aggregated for both refugee and IDP camps in out.csv. I could split this out, but this would result in additional columns containing zeroes for simulations that do not feature IDP camps. Would that be desirable?

**Comment by cspgdds** [comment]
@djgroen what do you mean by "additional columns containing zeroes for simulations that do not feature IDP camps"?  
We would like to compare total IDP counts for simulation and DTM. Also, we might not have validation for all IDP camps to visualise them individually.
