### ISSUE TITLE
'Camps' for suspectFLEE

### ISSUE THREAD

**Issue by irene-sophia** [djgroen/flee#63]
When does a suspect stop traveling? This should work slightly differently for a 'suspect-agent' than for a forced migration agent.

On their way, a suspect may encounter multiple POIs ( at which they may stop (parking garage, etc). At each of these, the suspect stops traveling with a certain probability attributed to the POI.

**Comment by djgroen** [comment]
Remind to self that "stop travelling" may mean deleting the agent from the simulation. This would require a bit of new code.

**Comment by djgroen** [comment]
Note: I am working on this now in a separate branch.
