### ISSUE TITLE
Adapt calculate_link_weights function to use graph attributes

### ISSUE THREAD

**Issue by irene-sophia** [djgroen/flee#64]
A suspect (especially hot-organized) chooses their next link based on its attributes: max_speed, road_type, traffic_density, etc.

**Comment by djgroen** [comment]
@irene-sophia Is there a particular equation you have in mind that would calculate the weight based on these factors?

I assume max_speed will be a value in km/h, and traffic density could be a value between 0.0 and 1.0. And I guess road types could by a list of types.

If you have an idea about what the equation should look like, then I'm happy to build it into Flee :).

**Comment by djgroen** [comment]
Superseded with a new type of ruleset request.
