### ISSUE TITLE
Allow for total number of agents to be spawned in each timestep to be conflict-dependent

### ISSUE THREAD

**Issue by MDI-SCI** [djgroen/flee#69]
Rather than use the conflict weights to distribute a set number of agents over the locations in the network, it would be great to have this total number of agents that are spawned to be dependent on conflict as well as it is likely that more newly displaced people would be added to the network if there is conflict in many locations

**Comment by djgroen** [comment]
I've now incorporated this for all kinds of spawning and pushed. Awaiting the integration tests... :)

**Comment by djgroen** [comment]
Okay, the tests appear to pass, though there could still be bugs. @MDI-SCI would you like to test it on your side?

**Comment by djgroen** [comment]
I believe this is working, so I will close this for now at least.
