### ISSUE TITLE
Pre-populating locations

### ISSUE THREAD

**Issue by MDI-SCI** [djgroen/flee#70]
Right now only locations tagged as camps can have a displaced population at the start of the simulation. As discussed today, it would be helpful if we can implement an extra input indicating how many agents should be in all of the locations at the start of the simulation, also if those locations are not camps but have different location types

**Comment by djgroen** [comment]
Low-level functionality + test add in 435f533

To do:
- [ ] integration into run script, using a SimulationSetting flag.
- [ ] documentation.

**Comment by djgroen** [comment]
@MDI-SCI I believe I have now implemented the required functionality. Would you perhaps like to test it out to see if it works sensibly for you? :)

**Comment by djgroen** [comment]
I believe this works as intended now.
