### ISSUE TITLE
Flee Validation Contest

### ISSUE THREAD

**Issue by djgroen** [djgroen/flee#80]
Share your validation results and simsetting.yml configurations here.

**Comment by mzrghorbani** [comment]
**Flee validation with simsetting configuration:**

log_levels:
  agent: 0
  camp: 0
  init: 0
spawn_rules:
  take_from_population: True
  conflict_spawn_decay: [1.0,1.0,1.0,0.5,0.1]
move_rules:
  start_on_foot: True
  avoid_short_stints: True
  awareness_level: 2
optimisations:

**And validation summary:**

Conflict venezuela2022_2024, Ave. rel. diff.: 0.33076406698869654, error: 0.16538203349434827
Conflict mali2012, Ave. rel. diff.: 0.5327366343307565, error: 0.26636831716537823
Conflict nigeria2022_2024, Ave. rel. diff.: 0.1259058648838336, error: 0.0629529324419168
Conflict ukraine2022_2024, Ave. rel. diff.: 0.21344111112734104, error: 0.10672055556367052
Conflict syria2022_2024, Ave. rel. diff.: 0.07388733142183637, error: 0.036943665710918186
Conflict ssudan2013, Ave. rel. diff.: 0.546071227919576, error: 0.273035613959788
Conflict nigeria2016, Ave. rel. diff.: 0.2517003000232622, error: 0.1258501500116311
Conflict ethiopia2020, Ave. rel. diff.: 0.407420096976111, error: 0.2037100484880555
Conflict mali2022_2024, Ave. rel. diff.: 0.09034140079981584, error: 0.04517070039990792
Conflict syria2013, Ave. rel. diff.: 0.2657352317598141, error: 0.13286761587990706
Conflict car2013, Ave. rel. diff.: 0.37231355085237267, error: 0.18615677542618633
Conflict burundi2015, Ave. rel. diff.: 0.404631596116492, error: 0.202315798058246
Conflict ssudan2016, Ave. rel. diff.: 0.5990229578375035, error: 0.29951147891875174
Averaged score: 0.32415164392595475

**Comment by mzrghorbani** [comment]
**Flee validation with simsetting configuration:**

log_levels:
  # Set the log level for agent-related information (0 = no information, 1 or higher = information logged)
  agent: 0 
  # Set the log level for link-related information (0 = no information, 1 or higher = information logged)
  link: 0 
  # Set the log level for camp-related information (0 = no information, 1 or higher = information logged)
  camp: 0
  # Set the log level for conflict-related information (0 = no information, 1 or higher = information logged)
  conflict: 0 
  # Set the log level for initialization-related information (0 = no information, 1 or higher = information logged)
  init: 0 

spawn_rules:
  # Allow spawned agents to be subtracted from populations (True or False)
  take_from_population: False
  # Insert agents at day 0 in camp locations (True or False)
  insert_day0: True
  # Spawns agents only from conflict zones when True; from all locations when False
  conflict_zone_spawning_only: True
  # Decaying factors for agents spawned from conflicts over time
  conflict_spawn_decay: [1.0, 1.0, 1.0, 0.5, 0.1]

move_rules:
  # Maximum speed agents can move in kilometres per time step
  max_move_speed: 360.0
  # Maximum speed agents can walk in kilometres per time step
  max_walk_speed: 35.0
  # Maximum speed agents can traverse while crossing (boat or walk) in kilometres per time step
  max_crossing_speed: 20.0
  # Attraction multiplier for foreign locations
  foreign_weight: 1.0
  # Attraction multiplier for camp locations
  camp_weight: 1.0
  # Attraction multiplier for conflict locations
  conflict_weight: 0.25
  # Chance of agents leaving conflict locations per day
  conflict_movechance: 1.0
  # Chance of agents leaving camp locations per day
  camp_movechance: 0.001
  # Chance of agents leaving regular locations per day
  default_movechance: 0.3
  # Chance of agents leaving internally displaced camps per day
  idpcamp_movechance: 0.1
  # Awareness level of agents for location presence (0 = none, 1 = most)
  awareness_level: 1
  # Factor to consider a location full based on (capacity OR pop) * CapacityBuffer
  capacity_buffer: 1
  # Allow agents to take breaks if they have travelled a full day's distance in the last two days (True or False)
  avoid_short_stints: False
  # Agents traverse the first link on foot (True or False)
  start_on_foot: False
  # Softening factor to reduce preference strength in choosing short routes
  softening: 10.0

optimisations:
  # Improve runtime performance by reducing the number of agents (0 = off, 1 = on)
  hasten: 1


**And validation summary:**

Conflict venezuela2022_2024, Ave. rel. diff.: 0.3200963186030157, error: 0.16004815930150784
Conflict mali2012, Ave. rel. diff.: 0.28287385752817346, error: 0.14143692876408673
Conflict nigeria2022_2024, Ave. rel. diff.: 0.07618499058389624, error: 0.03809249529194812
Conflict ukraine2022_2024, Ave. rel. diff.: 0.21852920544356721, error: 0.10926460272178361
Conflict syria2022_2024, Ave. rel. diff.: 0.06121353875107375, error: 0.030606769375536875
Conflict ssudan2013, Ave. rel. diff.: 0.43737750141981163, error: 0.21868875070990582
Conflict nigeria2016, Ave. rel. diff.: 0.18440160950347542, error: 0.09220080475173771
Conflict ethiopia2020, Ave. rel. diff.: 0.46663105442839353, error: 0.23331552721419677
Conflict mali2022_2024, Ave. rel. diff.: 0.0626350555742342, error: 0.0313175277871171
Conflict syria2013, Ave. rel. diff.: 0.28184147961771056, error: 0.14092073980885528
Conflict car2013, Ave. rel. diff.: 0.3042215330833978, error: 0.1521107665416989
Conflict burundi2015, Ave. rel. diff.: 0.5451308990701175, error: 0.27256544953505873
Conflict ssudan2016, Ave. rel. diff.: 0.7780769882866974, error: 0.3890384941433487
Averaged score: 0.3091703101456588

**Comment by mzrghorbani** [comment]
**Flee validation with simsetting configuration:**

log_levels:
  agent: 0 
  link: 0 
  camp: 0
  conflict: 0 
  init: 0 

spawn_rules:
  take_from_population: False
  insert_day0: True
  conflict_zone_spawning_only: True
  conflict_spawn_decay: [1.0, 1.0, 1.0, 0.5, 0.1]

move_rules:
  max_move_speed: 360.0
  max_walk_speed: 35.0
  max_crossing_speed: 20.0
  foreign_weight: 1.0
  camp_weight: 1.0
  conflict_weight: 0.25
  conflict_movechance: 1.0
  camp_movechance: 0.001
  default_movechance: 0.3
  idpcamp_movechance: 0.1
  awareness_level: 1
  capacity_buffer: 1
  avoid_short_stints: False
  start_on_foot: False
  softening: 10.0

optimisations:
  hasten: 1

**And validation summary:**

Conflict venezuela2022_2024, Ave. rel. diff.: 0.3200963186030157, error: 0.16004815930150784
Conflict mali2012, Ave. rel. diff.: 0.28287385752817346, error: 0.14143692876408673
Conflict nigeria2022_2024, Ave. rel. diff.: 0.07618499058389624, error: 0.03809249529194812
Conflict ukraine2022_2024, Ave. rel. diff.: 0.21852920544356721, error: 0.10926460272178361
Conflict syria2022_2024, Ave. rel. diff.: 0.06121353875107375, error: 0.030606769375536875
Conflict ssudan2013, Ave. rel. diff.: 0.43737750141981163, error: 0.21868875070990582
Conflict nigeria2016, Ave. rel. diff.: 0.18440160950347542, error: 0.09220080475173771
Conflict ethiopia2020, Ave. rel. diff.: 0.46663105442839353, error: 0.23331552721419677
Conflict mali2022_2024, Ave. rel. diff.: 0.0626350555742342, error: 0.0313175277871171
Conflict syria2013, Ave. rel. diff.: 0.28184147961771056, error: 0.14092073980885528
Conflict car2013, Ave. rel. diff.: 0.3042215330833978, error: 0.1521107665416989
Conflict burundi2015, Ave. rel. diff.: 0.5451308990701175, error: 0.27256544953505873
Conflict ssudan2016, Ave. rel. diff.: 0.7780769882866974, error: 0.3890384941433487
Averaged score: 0.3091703101456588

**Comment by mzrghorbani** [comment]
**Flee validation with simsetting configuration:**

    log_levels:
      agent: 0
      link: 0
      camp: 0
      conflict: 0
      init: 0
    
    spawn_rules:
      take_from_population: True
      insert_day0: True
      conflict_zone_spawning_only: True
      conflict_spawn_decay: [1.0, 1.0, 1.0, 0.5, 0.1]
    
    move_rules:
      max_move_speed: 360.0
      max_walk_speed: 35.0
      max_crossing_speed: 20.0
      foreign_weight: 1.0
      camp_weight: 1.0
      conflict_weight: 0.25
      conflict_movechance: 1.0
      camp_movechance: 0.001
      default_movechance: 0.3
      idpcamp_movechance: 0.1
      awareness_level: 1
      capacity_buffer: 1
      avoid_short_stints: False
      start_on_foot: False
      softening: 10.0
    
    optimisations:
      hasten: 1

**Validation Summary:**

Conflict venezuela2022_2024, Ave. rel. diff.: 0.31973557724750923, error: 0.15986778862375461
Conflict mali2012, Ave. rel. diff.: 0.28273762496472576, error: 0.14136881248236288
Conflict nigeria2022_2024, Ave. rel. diff.: 0.07649585581844387, error: 0.038247927909221935
Conflict ukraine2022_2024, Ave. rel. diff.: 0.21854054952840477, error: 0.10927027476420238
Conflict syria2022_2024, Ave. rel. diff.: 0.06131269334134155, error: 0.030656346670670773
Conflict ssudan2013, Ave. rel. diff.: 0.4355477849578343, error: 0.21777389247891715
Conflict nigeria2016, Ave. rel. diff.: 0.18262041552083025, error: 0.09131020776041512
Conflict ethiopia2020, Ave. rel. diff.: 0.4581511302385783, error: 0.22907556511928914
Conflict mali2022_2024, Ave. rel. diff.: 0.06266670054038904, error: 0.03133335027019452
Conflict syria2013, Ave. rel. diff.: 0.28292507464041067, error: 0.14146253732020533
Conflict car2013, Ave. rel. diff.: 0.3043535466983673, error: 0.15217677334918364
Conflict burundi2015, Ave. rel. diff.: 0.544918181981511, error: 0.2724590909907555
Conflict ssudan2016, Ave. rel. diff.: 0.7786102110282057, error: 0.38930510551410286
Averaged score: 0.30835502665435016

**Comment by mzrghorbani** [comment]
**Flee validation with simsetting configuration:**    

    log_levels:
      agent: 0
      camp: 0
      init: 0
    spawn_rules:
      take_from_population: True
      conflict_spawn_decay: [1.0,1.0,1.0,0.5,0.1]
    move_rules:
      start_on_foot: True
      avoid_short_stints: True
      awareness_level: 2
    optimisations:

**Validation Summary:**

Conflict venezuela2022_2024, Ave. rel. diff.: 0.5124986611393866, error: 0.2562493305696933
Conflict mali2012, Ave. rel. diff.: 0.5250492753853879, error: 0.26252463769269396
Conflict nigeria2022_2024, Ave. rel. diff.: 0.031316093717165594, error: 0.015658046858582797
Conflict nigeria2022_2024_adm2, Ave. rel. diff.: 0.1233228036167807, error: 0.06166140180839035
Conflict ukraine2022_2024, Ave. rel. diff.: 0.4528232253267661, error: 0.22641161266338306
Conflict syria2022_2024, Ave. rel. diff.: 0.07440572896219537, error: 0.037202864481097685
Conflict ssudan2013, Ave. rel. diff.: 0.5483767773837233, error: 0.27418838869186163
Conflict nigeria2016, Ave. rel. diff.: 0.25342116465006587, error: 0.12671058232503293
Conflict ethiopia2020, Ave. rel. diff.: 0.4076863699400731, error: 0.20384318497003656
Conflict mali2022_2024, Ave. rel. diff.: 0.09147224181402912, error: 0.04573612090701456
Conflict syria2013, Ave. rel. diff.: 0.26585610487341926, error: 0.13292805243670963
Conflict car2013, Ave. rel. diff.: 0.37182540312792933, error: 0.18591270156396467
Conflict burundi2015, Ave. rel. diff.: 0.4019686846989783, error: 0.20098434234948914
Conflict ssudan2016, Ave. rel. diff.: 0.6005715611278999, error: 0.30028578056394994
Averaged score: 0.3328995782688429

**Comment by alirezajahani60** [comment]
log_levels:
  agent: 0
  camp: 0
  init: 0
spawn_rules:
  take_from_population: True
  conflict_spawn_decay: [1.0,1.0,1.0,0.5,0.1]
move_rules:
  start_on_foot: True
  avoid_short_stints: True
  use_pop_for_loc_weight: True
  awareness_level: 1
  weight_power: 3
optimisations: 


VALIDATION SUMMARY:

Conflict nigeria2022_2024_adm2, Ave. rel. diff.: 0.02002683787591622, error: 0.01001341893795811
Conflict nigeria2016, Ave. rel. diff.: 0.6385100490638818, error: 0.3192550245319409
Conflict car2013, Ave. rel. diff.: 1.0879190996743902, error: 0.5439595498371951
Conflict mali2012, Ave. rel. diff.: 0.2878238214794887, error: 0.14391191073974435
Conflict burundi2015, Ave. rel. diff.: 1.582240791160512, error: 0.791120395580256
Conflict syria2022_2024, Ave. rel. diff.: 0.052057815200647964, error: 0.026028907600323982
Conflict venezuela2022_2024, Ave. rel. diff.: 0.36368704145780284, error: 0.18184352072890142
Conflict syria2013, Ave. rel. diff.: 0.44195184676312926, error: 0.22097592338156463
Conflict mali2022_2024, Ave. rel. diff.: 0.06024438943375251, error: 0.030122194716876254
Conflict ethiopia2020, Ave. rel. diff.: 0.7574968555952898, error: 0.3787484277976449
Conflict ukraine2022_2024, Ave. rel. diff.: 0.41608446938434746, error: 0.20804223469217373
Conflict ssudan2013, Ave. rel. diff.: 1.3703217165644468, error: 0.6851608582822234
Conflict ssudan2016, Ave. rel. diff.: 1.7809552331595955, error: 0.8904776165797977
Averaged score: 0.681486151293323

**Comment by alirezajahani60** [comment]
Here are the new results with the following configuration:

log_levels:
  agent: 0
  camp: 0
  conflict: 0
  init: 0
  link: 0
max_move_speed_values: 360.0
max_walk_speed_values: 35.0
move_rules:
  avoid_short_stints: false
  awareness_level: 1
  camp_movechance: 0.001
  camp_weight: 1.0
  capacity_buffer: 1
  conflict_movechance: 1.0
  conflict_weight: 0.25
  default_movechance: 0.3
  foreign_weight: 1.0
  idpcamp_movechance: 0.1
  max_crossing_speed: 20.0
  max_move_speed: 360.0
  max_walk_speed: 35.0
  softening: 10.0
  start_on_foot: false
optimisations:
  hasten: 1
spawn_rules:
  conflict_spawn_decay:
  - 1.0
  - 1.0
  - 1.0
  - 0.5
  - 0.1
  conflict_zone_spawning_only: true
  insert_day0: true
  take_from_population: false

VALIDATION SUMMARY:

Conflict nigeria2022_2024_adm2, Ave. rel. diff.: 0.038635714539872704, error: 0.019317857269936352
Conflict nigeria2016, Ave. rel. diff.: 0.1829211408482084, error: 0.0914605704241042
Conflict car2013, Ave. rel. diff.: 0.30447565294006057, error: 0.15223782647003029
Conflict mali2012, Ave. rel. diff.: 0.28431565018887245, error: 0.14215782509443622
Conflict burundi2015, Ave. rel. diff.: 0.5441780876433628, error: 0.2720890438216814
Conflict syria2022_2024, Ave. rel. diff.: 0.048213349439910465, error: 0.024106674719955232
Conflict venezuela2022_2024, Ave. rel. diff.: 0.33982317818374713, error: 0.16991158909187357
Conflict syria2013, Ave. rel. diff.: 0.28225740523240767, error: 0.14112870261620383
Conflict mali2022_2024, Ave. rel. diff.: 0.05337762726954237, error: 0.026688813634771186
Conflict ethiopia2020, Ave. rel. diff.: 0.46390492593154053, error: 0.23195246296577027
Conflict ukraine2022_2024, Ave. rel. diff.: 0.3986004687672715, error: 0.19930023438363575
Conflict ssudan2013, Ave. rel. diff.: 0.4337136924454186, error: 0.2168568462227093
Conflict ssudan2016, Ave. rel. diff.: 0.7811824781595197, error: 0.39059123907975984
Averaged score: 0.3196614901222873
