### ISSUE TITLE
Conflict driven spawning spawns agents without conflict

### ISSUE THREAD

**Issue by MDI-SCI** [djgroen/flee#88]
When enabling conflict driven spawning, the model keeps spawning the same number of agents even when all conflicts have already taken place. It would be helpful if the model only spawns agents on day that there's actually a conflict taking place, or if there would be a settings that lets the number of agents that are spawned as a consequence of a conflict decay over time

**Comment by djgroen** [comment]
Okay, I managed to discover the bug and I believe I've fixed it. I also refined the associated test case. Please give it a shot :)
